#!/bin/sh

# Xcode Cloud post-clone script.
#
# Chatter.xcodeproj is generated by XcodeGen from project.yml and is
# gitignored, so it does not exist in a fresh clone. Generate it here before
# Xcode Cloud tries to build.

set -e

echo "Installing XcodeGen..."
brew install xcodegen

cd "$CI_PRIMARY_REPOSITORY_PATH"

# TestFlight requires a unique, ascending build number per upload. Keep the
# project's <yyyymmdd>.<counter> scheme by combining today's date with the
# Xcode Cloud build number (which increments monotonically per workflow).
BUILD_NUMBER="$(TZ=Europe/Zurich date +%Y%m%d).${CI_BUILD_NUMBER}"
echo "Setting CURRENT_PROJECT_VERSION to ${BUILD_NUMBER}..."
sed -i '' "s/^\([[:space:]]*CURRENT_PROJECT_VERSION:\).*/\1 \"${BUILD_NUMBER}\"/" project.yml

echo "Generating Xcode project from project.yml..."
./generate.sh

# Xcode Cloud enables these defaults, which force the build to use a committed
# Package.resolved and disable on-the-fly SwiftPM resolution. Our .xcodeproj is
# XcodeGen-generated and gitignored, so there is no committed Package.resolved.
# Re-enable automatic resolution so the build resolves the MCP SDK itself.
# (`|| true`: the keys may be unset, and `defaults delete` would otherwise fail.)
echo "Re-enabling automatic SwiftPM resolution..."
defaults delete com.apple.dt.Xcode IDEPackageOnlyUseVersionsFromResolvedFile || true
defaults delete com.apple.dt.Xcode IDEDisableAutomaticPackageResolution || true

echo "ci_post_clone: done."
