import Foundation
import SwiftData

enum ArtifactKind: String, Codable, CaseIterable {
    case csv
    case markdown
    case code
}

/// A file generated by the model via the `artifact__create` tool, rendered in
/// the side panel (macOS) or a sheet (iOS). Content is stored inline as a
/// string — the provider caps it well under CloudKit's 1 MB record limit, so
/// artifacts sync with the session like messages do.
@Model
final class Artifact {
    var id: UUID = UUID()
    /// File name as passed by the model, e.g. "sales-q3.csv".
    var name: String = ""
    var kindRaw: String = ArtifactKind.code.rawValue
    var content: String = ""
    var createdAt: Date = Date()
    /// Links back to the `ToolCall.id` of the `artifact__create` call that
    /// produced this artifact, so the chat pill can find its artifact.
    var sourceToolCallID: String?

    var session: ChatSession?

    init(
        name: String,
        kind: ArtifactKind,
        content: String,
        sourceToolCallID: String? = nil
    ) {
        self.id = UUID()
        self.name = name
        self.kindRaw = kind.rawValue
        self.content = content
        self.createdAt = Date()
        self.sourceToolCallID = sourceToolCallID
    }

    var kind: ArtifactKind {
        get { ArtifactKind(rawValue: kindRaw) ?? .code }
        set { kindRaw = newValue.rawValue }
    }
}
